Created Output Log File: /workdir/tasks_run/data/logs/calculator_script_20240911_14h05m30s.txtdicom dir using: /workdir/tasks_run/data/sambashare/test_dir
Starting Block1 ... 
========================================
Starting Block1, Trial 1... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/86128545403926456204.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/86128545403926456204.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/86128545403926456204.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/15254460913022483476.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.0824890136719
Ending Block1, Trial 1... 
========================================
Starting Block1, Trial 2... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/15254460913022483476.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.0824890136719
Ending Block1, Trial 2... 
========================================
Starting Block1, Trial 3... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/91206890590912077378.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.45361328125
Ending Block1, Trial 3... 
========================================
Starting Block1, Trial 4... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83099551740379018390.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83099551740379018390.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83099551740379018390.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/88000613184130484908.dcm
nii_img_dtpye: int16
Mean ROI Activation: 434.17578125
Ending Block1, Trial 4... 
========================================
Starting Block1, Trial 5... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/88000613184130484908.dcm
nii_img_dtpye: int16
Mean ROI Activation: 434.17578125
Ending Block1, Trial 5... 
========================================
Starting Block1, Trial 6... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/98912951027985450771.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/98912951027985450771.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/98912951027985450771.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.2916259765625
Ending Block1, Trial 6... 
========================================
Starting Block1, Trial 7... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/52076994502218938594.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.1451721191406
Ending Block1, Trial 7... 
========================================
Starting Block1, Trial 8... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/96915363847876083941.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.8247375488281
Ending Block1, Trial 8... 
========================================
Starting Block1, Trial 9... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/75360362630081232576.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.1710205078125
Ending Block1, Trial 9... 
========================================
Starting Block1, Trial 10... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/15646250603056852296.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.77783203125
Ending Block1, Trial 10... 
========================================
Starting Block1, Trial 11... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/21034331143460140197.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/21034331143460140197.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/21034331143460140197.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/2022002501038172902.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.27960205078125
Ending Block1, Trial 11... 
========================================
Starting Block1, Trial 12... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/2022002501038172902.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.27960205078125
Ending Block1, Trial 12... 
========================================
Starting Block1, Trial 13... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/25220862119594753180.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.6358947753906
Ending Block1, Trial 13... 
========================================
Starting Block1, Trial 14... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/48698111775276342245.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.5789794921875
Ending Block1, Trial 14... 
========================================
Starting Block1, Trial 15... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/3096264064764849240.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.98370361328125
Ending Block1, Trial 15... 
========================================
Starting Block1, Trial 16... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/49934252242363287122.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.2542724609375
Ending Block1, Trial 16... 
========================================
Starting Block1, Trial 17... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/29560355686179299290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/29560355686179299290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/29560355686179299290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/96320874613318258301.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.5862731933594
Ending Block1, Trial 17... 
========================================
Starting Block1, Trial 18... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/96320874613318258301.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.5862731933594
Ending Block1, Trial 18... 
========================================
Starting Block1, Trial 19... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/8498092439996437652.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.8921813964844
Ending Block1, Trial 19... 
========================================
Starting Block1, Trial 20... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/74578686236814133290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/74578686236814133290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/74578686236814133290.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/89195040703263063974.dcm
nii_img_dtpye: int16
Mean ROI Activation: 436.0030212402344
Ending Block1, Trial 20... 
========================================
Starting Block1, Trial 21... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/89195040703263063974.dcm
nii_img_dtpye: int16
Mean ROI Activation: 436.0030212402344
Ending Block1, Trial 21... 
========================================
Starting Block1, Trial 22... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/39390421813531686497.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.888427734375
Ending Block1, Trial 22... 
========================================
Starting Block1, Trial 23... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/33094960772036540838.dcm
nii_img_dtpye: int16
Mean ROI Activation: 433.4012145996094
Ending Block1, Trial 23... 
========================================
Starting Block1, Trial 24... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/95249917384786736578.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.7673034667969
Ending Block1, Trial 24... 
========================================
Starting Block1, Trial 25... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/54192264920180839741.dcm
nii_img_dtpye: int16
Mean ROI Activation: 436.9265441894531
Ending Block1, Trial 25... 
========================================
Starting Block1, Trial 26... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/68680145535328301164.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/68680145535328301164.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/68680145535328301164.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/79251408934405699963.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.93304443359375
Ending Block1, Trial 26... 
========================================
Starting Block1, Trial 27... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/79251408934405699963.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.93304443359375
Ending Block1, Trial 27... 
========================================
Starting Block1, Trial 28... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/85960935239665990242.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.92352294921875
Ending Block1, Trial 28... 
========================================
Starting Block1, Trial 29... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/18729787752470298559.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
retrying after: 0.25s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/18729787752470298559.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
retrying after: 0.5s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/18729787752470298559.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 88, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
retrying after: 0.75s
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/19435155051912660643.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.8871765136719
Ending Block1, Trial 29... 
========================================
Starting Block1, Trial 30... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/19435155051912660643.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.8871765136719
Ending Block1, Trial 30... 
========================================
Starting Block1, Trial 31... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/17150106170747493924.dcm
nii_img_dtpye: int16
Mean ROI Activation: 433.4711608886719
Ending Block1, Trial 31... 
========================================
Starting Block1, Trial 32... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/42179748044042729389.dcm
nii_img_dtpye: int16
Mean ROI Activation: 433.2539978027344
Ending Block1, Trial 32... 
========================================
Starting Block1, Trial 33... 
========================================
Waiting For New File ...
---- Keyboard Interrupt Detected ----
What Would You Like to Do?
(1) Continue With The Block
(2) End The Session
(3) Start New Block
Ok, Let's End the Session...
Nifti Outdir Cleared
Ending Session Due to: keyboard interrupt
Session Data:
Running Main Calculation Script ... 
