Created Output Log File: /workdir/tasks_run/data/logs/calculator_script_20240911_14h34m50s.txtdicom dir using: /workdir/tasks_run/data/sambashare/test_dir
Starting Block1 ... 
========================================
Starting Block1, Trial 1... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/80513351925378223473.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/80513351925378223473.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/80513351925378223473.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Getting New Dicom Instead
Waiting For New File ...
New File Found In Dir...
Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/45313915074642033557.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.0824890136719
Ending Block1, Trial 1... 
========================================
Starting Block1, Trial 2... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/58911564340585351308.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.45361328125
Ending Block1, Trial 2... 
========================================
Starting Block1, Trial 3... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/38847191265958962796.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/38847191265958962796.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/38847191265958962796.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Getting New Dicom Instead
Waiting For New File ...
New File Found In Dir...
Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/14312649925410279051.dcm
nii_img_dtpye: int16
Mean ROI Activation: 434.17578125
Ending Block1, Trial 3... 
========================================
Starting Block1, Trial 4... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/76884315277788696446.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.2916259765625
Ending Block1, Trial 4... 
========================================
Starting Block1, Trial 5... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/46739387007967774609.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.1451721191406
Ending Block1, Trial 5... 
========================================
Starting Block1, Trial 6... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83340142969109433149.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.8247375488281
Ending Block1, Trial 6... 
========================================
Starting Block1, Trial 7... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/89457502649005582077.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.1710205078125
Ending Block1, Trial 7... 
========================================
Starting Block1, Trial 8... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/73339535390322331489.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.77783203125
Ending Block1, Trial 8... 
========================================
Starting Block1, Trial 9... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/54457724716391498790.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/54457724716391498790.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/54457724716391498790.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Getting New Dicom Instead
Waiting For New File ...
New File Found In Dir...
Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/25552516199891558597.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.27960205078125
Ending Block1, Trial 9... 
========================================
Starting Block1, Trial 10... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/72364796004448014256.dcm
nii_img_dtpye: int16
Mean ROI Activation: 429.6358947753906
Ending Block1, Trial 10... 
========================================
Starting Block1, Trial 11... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/85900949321805259122.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.5789794921875
Ending Block1, Trial 11... 
========================================
Starting Block1, Trial 12... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/73836382566876187572.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.98370361328125
Ending Block1, Trial 12... 
========================================
Starting Block1, Trial 13... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/51568430744963568855.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.2542724609375
Ending Block1, Trial 13... 
========================================
Starting Block1, Trial 14... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83513925265382147741.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83513925265382147741.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/83513925265382147741.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Getting New Dicom Instead
Waiting For New File ...
New File Found In Dir...
Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/75909834109865740052.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.5862731933594
Ending Block1, Trial 14... 
========================================
Starting Block1, Trial 15... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/18257336245780626749.dcm
nii_img_dtpye: int16
Mean ROI Activation: 430.8921813964844
Ending Block1, Trial 15... 
========================================
Starting Block1, Trial 16... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/7898825413647828663.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/7898825413647828663.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/7898825413647828663.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 94, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Getting New Dicom Instead
Waiting For New File ...
---- Keyboard Interrupt Detected ----
What Would You Like to Do?
(1) Continue With The Block
(2) End The Session
(3) Start New Block
Running Main Calculation Script ... 
