Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h06m12s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:05:30.851566
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h05m30s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,63
dicoms_in_dir,95
scripting_ending_time,2024-09-11 14:06:12.981903
script_total_time,0:00:42.130340
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:05:30.856646
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:05:30.859433
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/15254460913022483476.dcm
errors,"[('time_of_error: 20240911_14h05m37s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m37s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m37s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:38.873555
total_trial_time,0:00:08.014127
====== trial2 ======
trial_start_time,2024-09-11 14:05:38.876560
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/15254460913022483476.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:38.952821
total_trial_time,0:00:00.076265
====== trial3 ======
trial_start_time,2024-09-11 14:05:38.955679
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/91206890590912077378.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:39.280069
total_trial_time,0:00:00.324395
====== trial4 ======
trial_start_time,2024-09-11 14:05:39.283063
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/88000613184130484908.dcm
errors,"[('time_of_error: 20240911_14h05m40s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m40s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m41s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR4.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:42.010153
total_trial_time,0:00:02.727093
====== trial5 ======
trial_start_time,2024-09-11 14:05:42.013136
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/88000613184130484908.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR5.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:42.090876
total_trial_time,0:00:00.077744
====== trial6 ======
trial_start_time,2024-09-11 14:05:42.093743
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/98912951027985450771.dcm
errors,"[('time_of_error: 20240911_14h05m42s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m42s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,2
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR6.nii
mean_activation,431.29163
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:43.410954
total_trial_time,0:00:01.317216
====== trial7 ======
trial_start_time,2024-09-11 14:05:43.414121
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/52076994502218938594.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR7.nii
mean_activation,431.14517
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:43.489424
total_trial_time,0:00:00.075307
====== trial8 ======
trial_start_time,2024-09-11 14:05:43.492573
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/96915363847876083941.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR8.nii
mean_activation,429.82474
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:44.663047
total_trial_time,0:00:01.170479
====== trial9 ======
trial_start_time,2024-09-11 14:05:44.666131
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/75360362630081232576.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR9.nii
mean_activation,432.17102
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:45.713247
total_trial_time,0:00:01.047120
====== trial10 ======
trial_start_time,2024-09-11 14:05:45.716342
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/15646250603056852296.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR10.nii
mean_activation,432.77783
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:46.774377
total_trial_time,0:00:01.058040
====== trial11 ======
trial_start_time,2024-09-11 14:05:46.777331
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/2022002501038172902.dcm
errors,"[('time_of_error: 20240911_14h05m47s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m48s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m48s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR11.nii
mean_activation,432.2796
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:49.520107
total_trial_time,0:00:02.742780
====== trial12 ======
trial_start_time,2024-09-11 14:05:49.523036
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/2022002501038172902.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR12.nii
mean_activation,432.2796
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:49.599619
total_trial_time,0:00:00.076587
====== trial13 ======
trial_start_time,2024-09-11 14:05:49.602533
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/25220862119594753180.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR13.nii
mean_activation,429.6359
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:49.915372
total_trial_time,0:00:00.312844
====== trial14 ======
trial_start_time,2024-09-11 14:05:49.918245
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/48698111775276342245.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR14.nii
mean_activation,431.57898
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:50.986334
total_trial_time,0:00:01.068094
====== trial15 ======
trial_start_time,2024-09-11 14:05:50.989427
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/3096264064764849240.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR15.nii
mean_activation,430.9837
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:52.047945
total_trial_time,0:00:01.058523
====== trial16 ======
trial_start_time,2024-09-11 14:05:52.050890
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/49934252242363287122.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR16.nii
mean_activation,432.25427
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:53.119114
total_trial_time,0:00:01.068229
====== trial17 ======
trial_start_time,2024-09-11 14:05:53.122205
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/96320874613318258301.dcm
errors,"[('time_of_error: 20240911_14h05m54s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m54s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m55s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR17.nii
mean_activation,431.58627
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:55.886947
total_trial_time,0:00:02.764746
====== trial18 ======
trial_start_time,2024-09-11 14:05:55.889857
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/96320874613318258301.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR18.nii
mean_activation,431.58627
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:55.965629
total_trial_time,0:00:00.075777
====== trial19 ======
trial_start_time,2024-09-11 14:05:55.968528
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/8498092439996437652.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR19.nii
mean_activation,430.89218
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:56.288097
total_trial_time,0:00:00.319574
====== trial20 ======
trial_start_time,2024-09-11 14:05:56.290905
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/89195040703263063974.dcm
errors,"[('time_of_error: 20240911_14h05m57s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m57s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h05m58s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR20.nii
mean_activation,436.00302
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:59.048173
total_trial_time,0:00:02.757273
====== trial21 ======
trial_start_time,2024-09-11 14:05:59.051130
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/89195040703263063974.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR21.nii
mean_activation,436.00302
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:59.127738
total_trial_time,0:00:00.076613
====== trial22 ======
trial_start_time,2024-09-11 14:05:59.130671
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/39390421813531686497.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR22.nii
mean_activation,432.88843
successful_trial_end,True
ending_trial_time,2024-09-11 14:05:59.445336
total_trial_time,0:00:00.314670
====== trial23 ======
trial_start_time,2024-09-11 14:05:59.448502
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/33094960772036540838.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR23.nii
mean_activation,433.4012
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:00.520490
total_trial_time,0:00:01.071993
====== trial24 ======
trial_start_time,2024-09-11 14:06:00.523500
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/95249917384786736578.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR24.nii
mean_activation,430.7673
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:01.591047
total_trial_time,0:00:01.067552
====== trial25 ======
trial_start_time,2024-09-11 14:06:01.593911
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/54192264920180839741.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR25.nii
mean_activation,436.92654
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:02.654018
total_trial_time,0:00:01.060112
====== trial26 ======
trial_start_time,2024-09-11 14:06:02.656942
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/79251408934405699963.dcm
errors,"[('time_of_error: 20240911_14h06m03s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h06m03s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h06m04s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR26.nii
mean_activation,429.93304
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:05.421867
total_trial_time,0:00:02.764929
====== trial27 ======
trial_start_time,2024-09-11 14:06:05.424824
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/79251408934405699963.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR27.nii
mean_activation,429.93304
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:05.501295
total_trial_time,0:00:00.076477
====== trial28 ======
trial_start_time,2024-09-11 14:06:05.504359
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/85960935239665990242.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR28.nii
mean_activation,431.92352
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:05.823507
total_trial_time,0:00:00.319153
====== trial29 ======
trial_start_time,2024-09-11 14:06:05.826792
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/19435155051912660643.dcm
errors,"[('time_of_error: 20240911_14h06m06s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h06m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h06m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR29.nii
mean_activation,430.88718
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:08.554073
total_trial_time,0:00:02.727286
====== trial30 ======
trial_start_time,2024-09-11 14:06:08.557106
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/19435155051912660643.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR30.nii
mean_activation,430.88718
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:08.647753
total_trial_time,0:00:00.090651
====== trial31 ======
trial_start_time,2024-09-11 14:06:08.650683
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/17150106170747493924.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR31.nii
mean_activation,433.47116
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:09.081414
total_trial_time,0:00:00.430736
====== trial32 ======
trial_start_time,2024-09-11 14:06:09.084784
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/42179748044042729389.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR32.nii
mean_activation,433.254
successful_trial_end,True
ending_trial_time,2024-09-11 14:06:10.145265
total_trial_time,0:00:01.060485
====== trial33 ======
trial_start_time,2024-09-11 14:06:10.148454
keyboard_interrupt,2024-09-11 14:06:11.048690
block_end_time,2024-09-11 14:06:12.968489
total_block_time,0:00:42.111846
