Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h57m17s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:57:07.829307
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h57m07s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,256
dicoms_in_dir,260
scripting_ending_time,2024-09-11 14:57:17.976988
script_total_time,0:00:10.147684
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:57:07.834736
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:57:07.837692
this_trial_tries,3
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/34696466688789809923.dcm
errors,"[('time_of_error: 20240911_14h57m12s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 32, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 112, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h57m12s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 32, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 112, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
failed_dicoms,['/workdir/tasks_run/data/sambashare/test_dir/73413465622653788565.dcm']
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:57:13.954535
total_trial_time,0:00:06.116847
num_trials_with_errors,3
====== trial2 ======
trial_start_time,2024-09-11 14:57:13.957586
this_trial_tries,1
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/84048905510810050975.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:57:15.054336
total_trial_time,0:00:01.096755
====== trial3 ======
trial_start_time,2024-09-11 14:57:15.057265
this_trial_tries,2
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/64398245227446583796.dcm
errors,"[('time_of_error: 20240911_14h57m15s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 32, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 112, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
failed_dicoms,['/workdir/tasks_run/data/sambashare/test_dir/64398245227446583796.dcm']
keyboard_interrupt,2024-09-11 14:57:16.591361
block_end_time,2024-09-11 14:57:17.974244
total_block_time,0:00:10.139511
