Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h27m30s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:27:19.235820
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h27m19s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,148
dicoms_in_dir,152
scripting_ending_time,2024-09-11 14:27:30.845627
script_total_time,0:00:11.609809
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:27:19.239680
num_trials_failed,2
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:27:19.242459
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/93303414827030448094.dcm
errors,"[('time_of_error: 20240911_14h27m24s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m24s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m24s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m24s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:27:24.938249
total_trial_time,0:00:05.695793
====== trial2 ======
trial_start_time,2024-09-11 14:27:24.941000
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/11622520407786268170.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:27:25.905922
total_trial_time,0:00:00.964927
====== trial3 ======
trial_start_time,2024-09-11 14:27:25.908980
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/36983343217454900398.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:27:26.986638
total_trial_time,0:00:01.077663
====== trial4 ======
trial_start_time,2024-09-11 14:27:26.989716
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/53719175334178132689.dcm
errors,"[('time_of_error: 20240911_14h27m28s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m28s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m28s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h27m28s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:27:28.072997
total_trial_time,0:00:01.083284
====== trial5 ======
trial_start_time,2024-09-11 14:27:28.075819
keyboard_interrupt,2024-09-11 14:27:28.657499
block_end_time,2024-09-11 14:27:30.842745
total_block_time,0:00:11.603068
