Created Output Log File: /workdir/tasks_run/data/nfb_logs/p004_data_dictionary_20240912_13h40m40s.csv
====== whole_session_data ======
script_starting_time,2024-09-12 13:40:30.703849
sambashare_dir_path,/workdir/tasks_run/data/sambashare
starting_block,1
retries_before_ending,3
pid,p004
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
output_text_logfile_path,/workdir/tasks_run/data/nfb_logs/p004_calculator_script_20240912_13h40m30s.txt
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
log_directory_path,/workdir/tasks_run/data/nfb_logs
number_of_trials,140
starting_dicoms_in_dir,445
dicoms_in_dir,449
experimenter_screen_width,3390
experimenter_screen_height,1080
second_monitor_width,1920
second_monitor_height,1080
monitor_X_OFFSET,1920
monitor_Y_OFFSET,0
fixation_width,200
fixation_height,200
scripting_ending_time,2024-09-12 13:40:40.096216
script_total_time,0:00:09.392374
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-12 13:40:34.658164
num_trials_failed,0
nii_list,"[<nibabel.nifti1.Nifti1Image object at 0xffff7f3d9990>, <nibabel.nifti1.Nifti1Image object at 0xffff7f2c1d20>, <nibabel.nifti1.Nifti1Image object at 0xffff7f2c1d50>]"
event_dict,"  trial_type  onset  duration
0       rest    0.0      1.06"
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-12 13:40:34.674170
this_trial_tries,4
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/52570154271182693760.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,180.04852
errors,"[('time_of_error: 20240912_13h40m34s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 114, in get_resid\n    fmri_glm = fmri_glm.fit(run_imgs=concatNii, events=events, confounds=confounds)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/first_level.py"", line 587, in fit\n    design = make_first_level_design_matrix(frame_times,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/design_matrix.py"", line 384, in make_first_level_design_matrix\n    matrix, names = _convolve_regressors(\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/design_matrix.py"", line 243, in _convolve_regressors\n    reg, names = compute_regressor(\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/hemodynamic_models.py"", line 717, in compute_regressor\n    tr = _calculate_tr(frame_times)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/hemodynamic_models.py"", line 764, in _calculate_tr\n    return np.min(np.diff(frame_times))\n  File ""/usr/local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py"", line 3343, in min\n    return _wrapreduction(a, np.minimum, \'min\', axis, None, out,\n  File ""/usr/local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py"", line 86, in _wrapreduction\n    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\nValueError: zero-size array to reduction operation minimum which has no identity\n'), ('time_of_error: 20240912_13h40m35s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 117, in get_resid\n    predicted_data = fmri_glm.predicted(concatNii)\nTypeError: \'list\' object is not callable\n'), ('time_of_error: 20240912_13h40m36s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 117, in get_resid\n    predicted_data = fmri_glm.predicted(concatNii)\nTypeError: \'list\' object is not callable\n')]"
failed_dicoms,"['/workdir/tasks_run/data/sambashare/test_dir/88295789728078152705.dcm', '/workdir/tasks_run/data/sambashare/test_dir/51658527380539235380.dcm']"
keyboard_interrupt,2024-09-12 13:40:36.441665
num_trials_with_errors,3
block_end_time,2024-09-12 13:40:40.089062
total_block_time,0:00:05.430906
