Created Output Log File: /workdir/tasks_run/data/nfb_logs/p004_data_dictionary_20240912_14h09m03s.csv
====== whole_session_data ======
script_starting_time,2024-09-12 14:08:07.996494
sambashare_dir_path,/workdir/tasks_run/data/sambashare
starting_block,1
retries_before_ending,3
pid,p004
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
output_text_logfile_path,/workdir/tasks_run/data/nfb_logs/p004_calculator_script_20240912_14h08m07s.txt
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
log_directory_path,/workdir/tasks_run/data/nfb_logs
number_of_trials,140
starting_dicoms_in_dir,41
dicoms_in_dir,50
experimenter_screen_width,3390
experimenter_screen_height,1080
second_monitor_width,1920
second_monitor_height,1080
monitor_X_OFFSET,1920
monitor_Y_OFFSET,0
fixation_width,200
fixation_height,200
scripting_ending_time,2024-09-12 14:09:03.771190
script_total_time,0:00:55.774698
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-12 14:08:13.422554
num_trials_failed,1
nii_list,"[<nibabel.nifti1.Nifti1Image object at 0xffff68a75a20>, <nibabel.nifti1.Nifti1Image object at 0xffff68956860>, <nibabel.nifti1.Nifti1Image object at 0xffff68956b90>, <nibabel.nifti1.Nifti1Image object at 0xffff68957340>, <nibabel.nifti1.Nifti1Image object at 0xffff689577f0>, <nibabel.nifti1.Nifti1Image object at 0xffff689564d0>]"
event_dict,"  trial_type  onset  duration
0       rest   0.00      1.06
1       rest   1.06      1.06
2       rest   1.06      1.06"
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-12 14:08:13.439799
this_trial_tries,4
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/63622574064686032894.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,191.06981
errors,"[('time_of_error: 20240912_14h08m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 119, in get_resid\n    fmri_glm = fmri_glm.fit(run_imgs=concatNii, events=events, confounds=confounds)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/first_level.py"", line 587, in fit\n    design = make_first_level_design_matrix(frame_times,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/design_matrix.py"", line 384, in make_first_level_design_matrix\n    matrix, names = _convolve_regressors(\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/design_matrix.py"", line 243, in _convolve_regressors\n    reg, names = compute_regressor(\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/hemodynamic_models.py"", line 717, in compute_regressor\n    tr = _calculate_tr(frame_times)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/glm/first_level/hemodynamic_models.py"", line 764, in _calculate_tr\n    return np.min(np.diff(frame_times))\n  File ""/usr/local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py"", line 3343, in min\n    return _wrapreduction(a, np.minimum, \'min\', axis, None, out,\n  File ""/usr/local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py"", line 86, in _wrapreduction\n    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\nValueError: zero-size array to reduction operation minimum which has no identity\n'), ('time_of_error: 20240912_14h08m14s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 121, in get_resid\n    real_timeseries = masker.fit_transform(fmri_glm)\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 288, in fit_transform\n    return self.fit(**fit_params).transform(X,\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 232, in transform\n    return self.transform_single_imgs(imgs,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 542, in transform_single_imgs\n    data = self._cache(\n  File ""/usr/local/lib/python3.10/site-packages/joblib/memory.py"", line 312, in __call__\n    return self.func(*args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 80, in _filter_and_mask\n    temp_imgs = _utils.check_niimg(imgs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py"", line 316, in check_niimg\n    niimg = load_niimg(niimg, dtype=dtype)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg.py"", line 128, in load_niimg\n    raise TypeError(\nTypeError: Data given cannot be loaded because it is not compatible with nibabel format:\nP004_e3_registered...\n'), ('time_of_error: 20240912_14h08m15s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 121, in get_resid\n    real_timeseries = masker.fit_transform(fmri_glm)\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 288, in fit_transform\n    return self.fit(**fit_params).transform(X,\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 232, in transform\n    return self.transform_single_imgs(imgs,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 542, in transform_single_imgs\n    data = self._cache(\n  File ""/usr/local/lib/python3.10/site-packages/joblib/memory.py"", line 312, in __call__\n    return self.func(*args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 80, in _filter_and_mask\n    temp_imgs = _utils.check_niimg(imgs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py"", line 316, in check_niimg\n    niimg = load_niimg(niimg, dtype=dtype)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg.py"", line 128, in load_niimg\n    raise TypeError(\nTypeError: Data given cannot be loaded because it is not compatible with nibabel format:\nP004_e3_registered...\n'), ('time_of_error: 20240912_14h08m16s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 121, in get_resid\n    real_timeseries = masker.fit_transform(fmri_glm)\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 288, in fit_transform\n    return self.fit(**fit_params).transform(X,\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 232, in transform\n    return self.transform_single_imgs(imgs,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 542, in transform_single_imgs\n    data = self._cache(\n  File ""/usr/local/lib/python3.10/site-packages/joblib/memory.py"", line 312, in __call__\n    return self.func(*args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 80, in _filter_and_mask\n    temp_imgs = _utils.check_niimg(imgs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py"", line 316, in check_niimg\n    niimg = load_niimg(niimg, dtype=dtype)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg.py"", line 128, in load_niimg\n    raise TypeError(\nTypeError: Data given cannot be loaded because it is not compatible with nibabel format:\nP004_e3_registered...\n')]"
failed_dicoms,"['/workdir/tasks_run/data/sambashare/test_dir/93136185117942680452.dcm', '/workdir/tasks_run/data/sambashare/test_dir/72035137194362209246.dcm']"
successful_trial_end,False
ending_trial_time,2024-09-12 14:08:16.464602
total_trial_time,0:00:03.024813
num_trials_with_errors,6
====== trial2 ======
trial_start_time,2024-09-12 14:08:16.491532
this_trial_tries,3
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/4940659337548412634.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,180.19536
errors,"[('time_of_error: 20240912_14h08m17s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 121, in get_resid\n    real_timeseries = masker.fit_transform(fmri_glm)\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 288, in fit_transform\n    return self.fit(**fit_params).transform(X,\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 232, in transform\n    return self.transform_single_imgs(imgs,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 542, in transform_single_imgs\n    data = self._cache(\n  File ""/usr/local/lib/python3.10/site-packages/joblib/memory.py"", line 312, in __call__\n    return self.func(*args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 80, in _filter_and_mask\n    temp_imgs = _utils.check_niimg(imgs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py"", line 316, in check_niimg\n    niimg = load_niimg(niimg, dtype=dtype)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg.py"", line 128, in load_niimg\n    raise TypeError(\nTypeError: Data given cannot be loaded because it is not compatible with nibabel format:\nP004_e3_registered...\n'), ('time_of_error: 20240912_14h08m18s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 121, in get_resid\n    real_timeseries = masker.fit_transform(fmri_glm)\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 288, in fit_transform\n    return self.fit(**fit_params).transform(X,\n  File ""/usr/local/lib/python3.10/site-packages/sklearn/utils/_set_output.py"", line 313, in wrapped\n    data_to_wrap = f(self, X, *args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/base_masker.py"", line 232, in transform\n    return self.transform_single_imgs(imgs,\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 542, in transform_single_imgs\n    data = self._cache(\n  File ""/usr/local/lib/python3.10/site-packages/joblib/memory.py"", line 312, in __call__\n    return self.func(*args, **kwargs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py"", line 80, in _filter_and_mask\n    temp_imgs = _utils.check_niimg(imgs)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py"", line 316, in check_niimg\n    niimg = load_niimg(niimg, dtype=dtype)\n  File ""/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg.py"", line 128, in load_niimg\n    raise TypeError(\nTypeError: Data given cannot be loaded because it is not compatible with nibabel format:\nP004_e3_registered...\n')]"
failed_dicoms,['/workdir/tasks_run/data/sambashare/test_dir/91935265866228492227.dcm']
keyboard_interrupt,2024-09-12 14:08:18.901718
block_end_time,2024-09-12 14:09:03.766456
total_block_time,0:00:50.343918
